config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects, only: %i[index new create]
  resources :leads do
    get '/approve', to: 'leads#approve', as: 'approve'
    resources :phases, shallow: true do
      get '/new_engineer', to: 'phases#new_engineer', as: 'new_engineer'
      patch '/add_engineer_to_phase', to: 'phases#add_engineer_to_phase', as: 'add_engineer_to_phase'
      patch '/remove_engineer_from_phase', to: 'phases#remove_engineer_from_phase', as: 'remove_engineer_from_phase'
      patch '/approve', to: 'phases#approve', as: 'approve'
      get '/accepted', to: 'phases#accepted', as: 'accepted'
      resources :comments, shallow: true
    end
  end

  patch '/user_activate', to: 'users#activate', as: 'activate_account'
  patch '/user_disabled', to: 'users#disabled', as: 'disable_account'
  post '/comments/:id/delete_image/', to: 'comments#delete_image', as: 'delete_image'
  get '/users/:id/change_password', to: 'users#password_change', as: 'password_change'
  patch '/password_update/:id', to: 'users#password_update', as: 'password_update'

  root to: redirect('/users/sign_in')
  devise_for :users, controllers: { sessions: 'user/sessions' }

  resources :users

  get '*path', to: redirect('/'), code: 404
  # match '*path', to: redirect("#{Rails.root}/public/404"), via: :get, code: 404
  # get '*unmatched_route', to: 'leads#index', code: 404
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :phase
  has_many_attached :images
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  layout 'dashboard'
  include FlashMessages
  before_action :find_comment, only: %i[show edit update destroy delete_image] # rubocop:disable Rails/LexicallyScopedActionFilter
  before_action :find_phase, only: %i[new index create] # rubocop:disable Rails/LexicallyScopedActionFilter

  def new
    authorize @phase
    @comment = Comment.new
  end

  def create
    authorize @phase
    @comment = @phase.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      CommentMailer.with(comment: @comment, user: current_user).comment_create.deliver_later
      flash_message(I18n.t('comment.messages.create'), phase_path(@phase))
    else
      render new
    end
  end

  def edit
    unless (current_user == @comment.user) || (current_user.has_role? :BD) # rubocop:disable Style/GuardClause
      flash_message(I18n.t('common_errors.not_authorized'), phase_path(@comment.phase), 'error')
    end
  end

  def update
    if @comment.update(comment_params)
      CommentMailer.with(comment: @comment, user: current_user).comment_edit.deliver_later
      flash_message(I18n.t('comment.messages.update'), phase_path(@comment.phase))
    else
      render :edit
    end
  end

  def destroy
    @phase = @comment.phase
    @comment.destroy
    CommentMailer.with(comment: @comment, user: current_user).comment_deleted.deliver_later
    flash[:alert] = I18n.t('comment.messages.destroy')
  end

  def delete_image
    @comment.images.where(id: params[:format]).purge
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_text, images: [])
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def find_phase
    @phase = Phase.find(params[:phase_id])
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>">
  <b><p><%= comment.user.user_name %></p></b>
  <p><%= comment.comment_text %></td>
  <%= render 'comments/comment_images_show', comment: comment %>

  <div>
    <% if current_user %>
      <%= render 'comments/restricted_options', comment: comment %>
    <% end %>
  </div>
  <hr>
</div>

app/views/comments/_comment_form.html.erb
<div class="d-flex">
  <section class="form-auth auth-user">
    <% if comment.id %>
      <% @phase = Comment.find(params[:id]).phase %>
      <%= form_with model: comment, remote: true do |f| %>
        <% render 'comment_form_fields', f: f%>
      <% end %>
    <% else %>
      <% @phase = Phase.find(params[:phase_id]) %>
      <%= form_with( model: [@phase, @phase.comments.build], remote: true ) do |f| %>
        <% render 'comment_form_fields', f: f%>
      <% end %>
    <% end %>
  </section>

  <%= render 'comments/comment_images_edit', comment: @comment %>
</div>

app/views/comments/_comment_form_fields.html.erb
<b><p class="mb-3 font-weight-normal">Comment Description</p></b>
<%= f.text_area :comment_text, autofocus: true, rows: 10, cols: 60, class: "form-control", placeholder: "Comment Description",accept: 'image/jpeg', required:true %>
<%= f.file_field :images, multiple: :true %>

<button class="btn btn-lg btn-primary btn-block" type="submit">Add Comment</button><br>

app/views/comments/_comment_images.html.erb
<div>
  <% @comment = locals[:comment]%>
  <% if @comment.images.attached? %>
    <ul class="comment_images d-flex">
      <% @comment.images.each do |image| %>
        <li id="comment_image_<%= image.id %>">
          <%= cl_image_tag(image.key, width: 300)  %>
          <%= link_to 'Remove Image', delete_image_path(@comment, image), class: "btn btn-danger", remote: true, method: :post if locals[:edit_method] %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/comments/_comment_images_edit.html.erb
<%= render 'comments/comment_images', locals: {comment: comment, edit_method: true} %>

app/views/comments/_comment_images_show.html.erb
<%= render 'comments/comment_images', locals: {comment: comment, edit_method: false} %>

app/views/comments/_restricted_options.html.erb
<% if current_user == comment.user or current_user.has_role? :BD %>
  <%= link_to 'Edit', edit_comment_path(comment), class: "btn btn-secondary" %>
  <%= link_to 'Delete', comment_path(comment),
        method: :delete,
        data: { confirm: 'Are you sure?' }, class: "btn btn-danger",remote: true %>
<% end %>

app/views/comments/delete_image.js.erb
$("#comment_image_<%= params[:format] %>").remove()

app/views/comments/destroy.js.erb
$("#comment_<%= @comment.id %>").remove()

app/views/comments/edit.html.erb
<h3 class="h3 mb-3 font-weight-normal">Edit Comment</h3>
<%= render "comment_form", comment: @comment %>

<%= render 'shared/back_navigation', path: phase_path(@phase) %>

app/views/comments/new.html.erb
<h3 class="h3 mb-3 font-weight-normal">Add Comment</h3>
<%= render "comment_form", comment: @comment %>

<%= render 'shared/back_navigation', path: phase_path(@phase) %>