config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects, only: %i[index new create]
  resources :leads do
    get '/approve', to: 'leads#approve', as: 'approve'
    resources :phases, shallow: true do
      get '/new_engineer', to: 'phases#new_engineer', as: 'new_engineer'
      patch '/add_engineer_to_phase', to: 'phases#add_engineer_to_phase', as: 'add_engineer_to_phase'
      patch '/remove_engineer_from_phase', to: 'phases#remove_engineer_from_phase', as: 'remove_engineer_from_phase'
      patch '/approve', to: 'phases#approve', as: 'approve'
      get '/accepted', to: 'phases#accepted', as: 'accepted'
      resources :comments, shallow: true
    end
  end

  patch '/user_activate', to: 'users#activate', as: 'activate_account'
  patch '/user_disabled', to: 'users#disabled', as: 'disable_account'
  post '/comments/:id/delete_image/', to: 'comments#delete_image', as: 'delete_image'
  get '/users/:id/change_password', to: 'users#password_change', as: 'password_change'
  patch '/password_update/:id', to: 'users#password_update', as: 'password_update'

  root to: redirect('/users/sign_in')
  devise_for :users, controllers: { sessions: 'user/sessions' }

  resources :users

  get '*path', to: redirect('/'), code: 404
  # match '*path', to: redirect("#{Rails.root}/public/404"), via: :get, code: 404
  # get '*unmatched_route', to: 'leads#index', code: 404
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :projects # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :leads # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :comments, dependent: :nullify

  after_create :add_role_to_user
  validates :user_name, presence: true
  validates :email, presence: true
  validates :user_role, presence: true

  private

  def add_role_to_user
    case user_role
    when 'admin'
      add_admin_role

    when 'BD'
      add_bd_role

    when 'TM'
      add_tm_role
    end
    add_engineer_role
  end

  def add_admin_role
    add_role :admin
    add_bd_role
  end

  def add_bd_role
    add_role :BD
    add_tm_role
  end

  def add_tm_role
    add_role :TM
    add_engineer_role
  end

  def add_engineer_role
    add_role :engineer
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  layout 'dashboard'

  def after_sign_up_path_for(dashboard_path) # rubocop:disable Lint/UselessMethodDefinition
    super(dashboard_path)
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(_resource)
    redirect_to '/dashboard'
    # super(resource)
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    if !User.find_by(email: params[:user][:email]).active
      redirect_to new_user_session_path
    else
      super
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  layout 'dashboard'
  before_action :find_user, only: %i[edit update password_change] # rubocop:disable Rails/LexicallyScopedActionFilter
  before_action :find_user_for_custom_action, only: %i[activate disabled]
  before_action :check_user_auth, only: %i[edit update] # rubocop:disable Rails/LexicallyScopedActionFilter

  def index
    @users = User.order(:user_role).page(params[:page]).per(10)
    authorize @users
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user
    if @user.save
      UserMailer.with(admin: current_user, user: @user).user_created.deliver_later
      redirect_to users_path
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_update_params)
      current_user.has_role?(:admin) ? (redirect_to users_path) : (redirect_to leads_path)
    else
      render :edit
    end
  end

  def disabled
    authorize @user, :update?
    @user.toggle!(:active) # rubocop:disable Rails/SkipsModelValidations
  end

  def activate
    authorize @user, :update?
    @user.toggle!(:active) # rubocop:disable Rails/SkipsModelValidations
  end

  def password_change; end

  def password_update
    @user = current_user
    if @user.update(user_update_password_params)
      if current_user.has_role? :admin
        redirect_to users_path
      else
        redirect_to destroy_user_session_path
      end
    else
      render :password_change
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :user_role, :email, :password, :password_confirmation)
  end

  def user_update_params
    params.require(:user).permit(:user_name, :user_role, :email)
  end

  def user_update_password_params
    params.permit(:password, :password_confirmation)
  end

  def find_user
    @user = User.find(params[:id])
  end

  def check_user_auth
    authorize @user if current_user && (current_user.id != @user.id)
  end

  def find_user_for_custom_action
    @user = User.find(params[:format])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def admin?
    current_user.has_role? :admin
  end

  def BD? # rubocop:disable Naming/MethodName
    current_user.has_role? :BD
  end
end

app/views/users/_user_form.html.erb
<section class="form-auth auth-user">
  <%= form_for @user, local: true do |f| %>
    <%= render "devise/shared/error_messages", resource: @user %>

    <%= f.text_field :user_name, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "Full Name", required: true %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "Email address", disabled: !admin? %>
    <%= f.select :user_role, ['admin', 'BD', 'TM', 'engineer'],{ prompt: "Please select User Role" }, autofocus: true, class: "form-control", selected: user.user_role, disabled: !admin? %>
    <%= f.password_field :password , class: "form-control", placeholder: "Password (Minimum 6 character)" if @user.new_record? %>
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" if @user.new_record? %>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button><br>
  <% end %>
</section>

app/views/users/activate.js.erb
$("#user_status_<%= @user.id %>").replaceWith('<td id="user_status_<%= @user.id %>"><%= link_to "Disable", disable_account_path(@user),
              method: :patch, data: { confirm: "Are you sure?" }, class: "btn btn-danger", remote: true %></td>')

app/views/users/disabled.js.erb
$("#user_status_<%= @user.id %>").replaceWith('<td id="user_status_<%= @user.id %>"><%= link_to "Activate", activate_account_path(@user),
              method: :patch, data: { confirm: "Are you sure?" }, class: "btn btn-success", remote: true %></td>')

app/views/users/edit.html.erb
<h1 class="h1 mb-3 font-weight-normal">Edit User</h1>
<%= render "user_form", user: @user %>

<%= link_to 'Change Password', password_change_path(@user), class: "btn btn-info" %>
<%= render 'shared/back_navigation', path: leads_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Sr.</th>
      <th scope="col">User Name</th>
      <th scope="col">User Email</th>
      <th scope="col">User Role</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <tr>
  </tr>
  </thead>
  <tbody>
    <% @id = 0%>
    <% @users.each do |user| %>
    <% @id += 1 %>
      <tr>
        <th scope="row"><%= @id %></th>
        <td><%= user.user_name %></td>
        <td><%= user.email %></td>
        <td><%= user.user_role %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-secondary" %></td>
        <% if user.active %>
          <td id="user_status_<%= user.id %>"><%= link_to 'Disable', disable_account_path(user) ,
              method: :patch,
              data: { confirm: 'Are you sure?' }, class: "btn btn-danger", remote: true %>
              </td>
        <% else %>
          <td id="user_status_<%= user.id %>"><%= link_to 'Activate', activate_account_path(user),
              method: :patch,
              data: { confirm: 'Are you sure?' }, class: "btn btn-success", remote: true %>
              </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/users/new.html.erb
<h1 class="h1 mb-3 font-weight-normal">Create User</h1>
<%= render "user_form", user: @user %>

<%= render 'shared/back_navigation', path: users_path %>

app/views/users/password_change.html.erb
<section class="form-auth auth-user">
  <h2>Change Password</h2>
  <%= form_with url: password_update_path(@user), method: :patch do |f| %>
    <%= render "devise/shared/error_messages", resource: @user %>

    <%= f.password_field :password , class: "form-control", placeholder: "Password (Minimum 6 character)" %>
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button><br>
  <% end %>
</section>