config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects, only: %i[index new create]
  resources :leads do
    get '/approve', to: 'leads#approve', as: 'approve'
    resources :phases, shallow: true do
      get '/new_engineer', to: 'phases#new_engineer', as: 'new_engineer'
      patch '/add_engineer_to_phase', to: 'phases#add_engineer_to_phase', as: 'add_engineer_to_phase'
      patch '/remove_engineer_from_phase', to: 'phases#remove_engineer_from_phase', as: 'remove_engineer_from_phase'
      patch '/approve', to: 'phases#approve', as: 'approve'
      get '/accepted', to: 'phases#accepted', as: 'accepted'
      resources :comments, shallow: true
    end
  end

  patch '/user_activate', to: 'users#activate', as: 'activate_account'
  patch '/user_disabled', to: 'users#disabled', as: 'disable_account'
  post '/comments/:id/delete_image/', to: 'comments#delete_image', as: 'delete_image'
  get '/users/:id/change_password', to: 'users#password_change', as: 'password_change'
  patch '/password_update/:id', to: 'users#password_update', as: 'password_update'

  root to: redirect('/users/sign_in')
  devise_for :users, controllers: { sessions: 'user/sessions' }

  resources :users

  get '*path', to: redirect('/'), code: 404
  # match '*path', to: redirect("#{Rails.root}/public/404"), via: :get, code: 404
  # get '*unmatched_route', to: 'leads#index', code: 404
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lead.rb
# frozen_string_literal: true

class Lead < ApplicationRecord
  belongs_to :user
  has_one :project # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :phases,  dependent: :destroy

  validates :lead_name, presence: true, length: { minimum: 5 }
  validates :platform_used, presence: true, length: { minimum: 3 }
  validates :lead_type, presence: true
  validates :client_name, presence: true
  validates :client_contact, format: { with: /\A\d{11}\z/ }
end

app/controllers/leads_controller.rb
# frozen_string_literal: true

class LeadsController < ApplicationController
  layout 'dashboard'
  include FlashMessages

  before_action :find_lead, only: %i[show edit update destroy] # rubocop:disable Rails/LexicallyScopedActionFilter

  def index
    @leads = Lead.where(is_sale: false).page(params[:page]).per(10)
  end

  def new
    @lead = Lead.new
    authorize @lead
  end

  def create
    @lead = Lead.new(lead_params)
    authorize @lead
    @lead.user = current_user
    if @lead.save
      LeadMailer.with(lead: @lead).lead_created.deliver_later
      flash_message(I18n.t('leads.messages.create'), @lead)
    else
      render 'new'
    end
  end

  def update
    if @lead.update(lead_params)
      LeadMailer.with(lead: @lead, admin: current_user).lead_update.deliver_later
      flash_message(I18n.t('leads.messages.update'), @lead)
    else
      render 'edit'
    end
  end

  def destroy
    @lead.destroy
    LeadMailer.with(lead: @lead, admin: current_user).lead_deleted.deliver_later
    flash[:alert] = I18n.t('leads.messages.destroy')
  end

  def approve
    @lead = Lead.find(params[:lead_id])
    authorize @lead, :update?
    if check_lead
      redirect_to new_project_path(lead_id: @lead.id)
    else
      flash_message(I18n.t('leads.messages.phase_approved'), leads_path, 'error')
    end
  end

  private

  def lead_params
    params.require(:lead).permit(:lead_name, :lead_type, :platform_used, :client_name, :client_address, :client_email,
                                 :client_contact)
  end

  def find_lead
    @lead = Lead.find(params[:id])
    authorize @lead
  end

  def check_lead
    @phases = @lead.phases
    @phases.each do |phase|
      next unless phase.approved == false

      return false
    end
    true
  end
end

app/views/leads/_client_details.html.erb
<div class="client_detail">
  <h3>Client Information</h3>
  <p>Client Name : <%= @lead.client_name%></p>
  <p>Client Email : <%= @lead.client_email%></p>
  <p>Client Address : <%= @lead.client_address%></p>
  <p>Client Contact No : <%= @lead.client_contact%></p>
</div>

app/views/leads/_form.html.erb
<section class="form-auth auth-user">
  <%= form_with model: lead, local: true do |f| %>
    <%= render "devise/shared/error_messages", resource: lead %>

    <h4 class="h4 mb-3 font-weight-normal">Lead Info</h4>
    <%= f.text_field :lead_name, autofocus: true, class: "form-control", placeholder: "Lead Name", required:true %>
    <%= f.text_field :lead_type, autofocus: true, class: "form-control", placeholder: "Lead Type", required:true %>
    <%= f.text_field :platform_used, autofocus: true, class: "form-control", placeholder: "Platform" %>
    <h4 class="h4 mb-3 font-weight-normal">Client Info</h4>
    <%= f.text_field :client_name, autofocus: true, class: "form-control", placeholder: "Client Name", required:true%>
    <%= f.text_field :client_address, autofocus: true, class: "form-control", placeholder: "Client Address"%>
    <%= f.email_field :client_email, autofocus: true, class: "form-control", placeholder: "Client Email",required:true %>
    <%= f.text_field :client_contact, autofocus: true, class: "form-control", placeholder: "Client Contact", required:true %>

    <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button><br>
  <% end %>
</section>

app/views/leads/_lead_details.html.erb
<div class="lead_detail">
  <h3>Lead Detail</h3>
  <p>Lead Name : <%= @lead.lead_name%></p>
  <p>Lead Name : <%= @lead.lead_type%></p>
  <p>Platform :<%= @lead.platform_used%></p>
  <p>Owner : <%= @lead.user.user_name%></p>
</div>

app/views/leads/_restricted_options.html.erb
<td><%= link_to 'Convert To Sale', lead_approve_path(lead),
    data: { confirm: 'Are you sure?' }, class: "btn btn-info" %></td>

<td><%= link_to 'Edit', edit_lead_path(lead), class: "btn btn-secondary" %></td>
<td><%= link_to 'Delete', lead_path(lead),
      method: :delete,
      data: { confirm: 'Are you sure?' }, class: "btn btn-danger", remote: true %></td>

app/views/leads/destroy.js.erb
$("#lead_<%= @lead.id %>").remove()

app/views/leads/edit.html.erb
<h3>Edit Lead</h3>

<%= render "form", lead: @lead %>
<%= render 'shared/back_navigation', path: leads_path %>

app/views/leads/index.html.erb
<h2>Leads</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Sr.</th>
      <th scope="col">Lead Name</th>
      <th scope="col">Lead Type</th>
      <th scope="col">Platform</th>
      <th scope="col">Client Name</th>
      <th scope="col">Owner</th>
      <th colspan='4'>Actions</th>
    </tr>
    <tr>
  </tr>
  </thead>
  <tbody>
    <% @id = 0 %>
    <% @leads.each do |lead| %>
    <% @id += 1 %>
      <tr id="lead_<%= lead.id %>">
        <th scope="row"><%= @id %></th>
        <td><%= lead.lead_name %></td>
        <td><%= lead.lead_type %></td>
        <td><%= lead.platform_used %></td>
        <td><%= lead.client_name %></td>
        <td><%= lead.user.user_name %></td>
        <td><%= link_to 'View', lead_path(lead),class: "btn btn-primary" %></td>
        <% if policy(Lead).update? %>
          <%= render 'restricted_options', lead: lead %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @leads %>

app/views/leads/new.html.erb
<h3 class="h2 mb-3 font-weight-normal">Create Lead</h3>
<%= render "form", lead: @lead %>
<%= render 'shared/back_navigation', path: leads_path %>

app/views/leads/show.html.erb
<div class="d-flex show_container">
  <%= render "lead_details", lead: @lead %>
  <%= render "client_details", lead: @lead %>
</div>

<% if current_user %>
  <% if current_user.has_role? :BD %>
    <%= link_to 'Create Phase', new_lead_phase_path(@lead),class: "btn btn-primary" %>
  <% end %>
<% end %>
<%= link_to 'Show All Phases', lead_phases_path(@lead) ,class: "btn btn-primary" %>
<%= render 'shared/back_navigation', path: leads_path %>