config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects, only: %i[index new create]
  resources :leads do
    get '/approve', to: 'leads#approve', as: 'approve'
    resources :phases, shallow: true do
      get '/new_engineer', to: 'phases#new_engineer', as: 'new_engineer'
      patch '/add_engineer_to_phase', to: 'phases#add_engineer_to_phase', as: 'add_engineer_to_phase'
      patch '/remove_engineer_from_phase', to: 'phases#remove_engineer_from_phase', as: 'remove_engineer_from_phase'
      patch '/approve', to: 'phases#approve', as: 'approve'
      get '/accepted', to: 'phases#accepted', as: 'accepted'
      resources :comments, shallow: true
    end
  end

  patch '/user_activate', to: 'users#activate', as: 'activate_account'
  patch '/user_disabled', to: 'users#disabled', as: 'disable_account'
  post '/comments/:id/delete_image/', to: 'comments#delete_image', as: 'delete_image'
  get '/users/:id/change_password', to: 'users#password_change', as: 'password_change'
  patch '/password_update/:id', to: 'users#password_update', as: 'password_update'

  root to: redirect('/users/sign_in')
  devise_for :users, controllers: { sessions: 'user/sessions' }

  resources :users

  get '*path', to: redirect('/'), code: 404
  # match '*path', to: redirect("#{Rails.root}/public/404"), via: :get, code: 404
  # get '*unmatched_route', to: 'leads#index', code: 404
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/phases_controller.rb
# frozen_string_literal: true

class PhasesController < ApplicationController
  layout 'dashboard'
  include FlashMessages
  before_action :find_phase, only: %i[show edit update destroy] # rubocop:disable Rails/LexicallyScopedActionFilter
  before_action :find_lead, only: %i[index create]
  before_action :find_phase_for_custom_action,
                only: %i[new_engineer approve accepted add_engineer_to_phase remove_engineer_from_phase]

  def index
    @phases = @lead.phases
  end

  def new
    @phase = Phase.new
    authorize @phase
  end

  def create
    @phase = @lead.phases.build(phase_params)
    authorize @phase
    if @phase.save
      PhaseMailer.with(phase: @phase, admin: current_user).phase_created.deliver_later
      PhaseMailer.with(phase: @phase, admin: current_user).phase_assigned_TM.deliver_later
      flash_message(I18n.t('phases.messages.create'), @phase)
    else
      render 'new'
    end
  end

  def update
    if @phase.update(phase_params)
      PhaseMailer.with(phase: @phase, admin: current_user).phase_update.deliver_later
      flash_message(I18n.t('phases.messages.update'), @phase)
    else
      render :edit
    end
  end

  def destroy
    @phase.destroy
    PhaseMailer.with(phase: @phase, admin: current_user).phase_deleted.deliver_later
    flash[:alert] = I18n.t('phases.messages.destroy')
  end

  def approve
    authorize @phase, :update?
    PhaseMailer.with(phase: @phase, admin: current_user).phase_status.deliver_later if @phase.toggle!(:approved) # rubocop:disable Rails/SkipsModelValidations
  end

  def accepted
    redirect_to phase_path(@phase) if @phase.toggle!(:is_accepted) # rubocop:disable Rails/SkipsModelValidations
    redirect_to lead_phases_path(@phase.lead)
  end

  def new_engineer; end

  def add_engineer_to_phase
    authorize @phase
    @arr = []
    @arr << @phase.assigned_engineer if @phase.assigned_engineer
    @arr << params[:user_id]
    @phase.assigned_engineer = @arr.flatten.uniq
    flash_message(I18n.t('common_errors.unknown_error'), phase_add_engineer_path(@phase), 'alert') unless @phase.save
  end

  def remove_engineer_from_phase
    authorize @phase
    if @phase.assigned_engineer.empty?
      flash_message(I18n.t('phases.messages.empty_engineer_list'), phase_add_engineer_path(@phase), 'alert')
    end
    @arr = @phase.assigned_engineer
    @arr.delete(params[:user_id])
    @phase.assigned_engineer = @arr
    flash_message(I18n.t('common_errors.unknown_error'), phase_add_engineer_path(@phase), 'alert') unless @phase.save
  end

  private

  def phase_params
    params.require(:phase).permit(:phase_type, :start_date, :end_date, :user_id)
  end

  def find_phase
    @phase = Phase.find(params[:id])
    authorize @phase
  end

  def find_phase_for_custom_action
    @phase = Phase.find(params[:phase_id])
  end

  def find_lead
    @lead = Lead.find(params[:lead_id])
  end
end

app/helpers/phases_helper.rb
# frozen_string_literal: true

module PhasesHelper
  def all_tech_manager
    User.where(user_role: 'TM', active: true)
  end

  def all_engineer
    User.where(user_role: 'engineer', active: true)
  end

  def find_all_engineer_of_phase(arr)
    all_id_array = arr.delete_if { |x| x == '' }
    all_id_array.map { |x| User.find(x).user_name }
  end

  def check_add_engineer(phase, _user)
    if phase.approved
      false
    else
      phase.is_accepted && (current_user == phase.user) || BD?
    end
  end
end

app/views/phases/_all_comments.html.erb
<div class="flex_space_between">
  <h4>Comments</h4>
  <div class="comment_button">
    <% if current_user %>
      <%= link_to 'Add Comment', new_phase_comment_path(@phase) , class: "btn btn-primary" %>
    <% end %>
    <%= render 'shared/back_navigation', path: lead_phases_path(@phase.lead)  %>
  </div>
</div>
<%= render  @phase.comments %>

app/views/phases/_phase_details.html.erb
<h3>Phase Detail</h3>
<b><p>Lead Name : <%= @phase.lead.lead_name%></p></b>
<p>Phase Type : <%= @phase.phase_type %></p>
<p>Start Date : <%= @phase.start_date %></p>
<p>End Date : <%= @phase.end_date %></p>
<p>Assigned Technical Manager : <%= @phase.user.user_name %></p>

app/views/phases/_phase_form.html.erb
<section class="form-auth auth-user">
  <% if phase.id %>
    <% @lead = Phase.find(params[:id]).lead %>
    <%= form_with model: @phase, local: true do |f| %>
      <% render 'phase_form_fields', f: f%>
    <% end %>
  <% else %>
    <% @lead = Lead.find(params[:lead_id]) %>
    <%= form_with( model: [@lead, @lead.phases.build], local: true) do |f| %>
      <% render 'phase_form_fields', f: f%>
    <% end %>
  <% end %>
</section>

app/views/phases/_phase_form_fields.html.erb
<% if @phase.errors.any? %>
  <div>
    <h2>
      <%= pluralize(@phase.errors.count, "error") %> prohibited
      this Phase from being Saved:
    </h2>
    <ul>
      <% @phase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= f.label :phase_type %>:
<%= f.select :phase_type, ['test project', 'interview'],{ prompt: "Please select Phase Type"}, autofocus: true, class: "form-control", selected: @phase.phase_type %>

<div class='flex_space_between'>
  <%= f.label :start_date %>:
  <div><%= f.date_select :start_date, start_year: Date.current().year, autofocus: true, class: "form-control" %></div>
</div>
<div class="flex_space_between">
  <%= f.label :end_date %>:
  <div class><%= f.date_select :end_date, start_year: Date.current().year ,autofocus: true, class: "form-control" %></div>
</div>
<div>
  <%= f.collection_select :user_id, all_tech_manager, :id, :user_name,{ prompt: "Please select Technical Manager"}, autofocus: true, class: "form-control" %>
</div>
<% if params[:id] %>
  <div>
    <%= f.label :approved %>:
    <%= f.check_box :approved, class: 'checkbox' %>
  </div>
<% end %>

<button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button><br>

app/views/phases/_restricted_options.html.erb
<% if !phase.approved %>
  <% if (phase.end_date - Date.current).to_i.negative? %>
    <td><%= link_to 'Expired', phase_approve_path(phase),
        data: { confirm: 'Are you sure?' }, class: "btn btn-warning",id: "phase_approve_#{phase.id}" ,remote: true, method: :patch %></td>
  <% else %>
    <td><%= link_to 'Approve', phase_approve_path(phase),
        data: { confirm: 'Are you sure?' }, class: "btn btn-info",id: "phase_approve_#{phase.id}" ,remote: true, method: :patch %></td>
  <% end %>
<% else %>
  <td><button class="btn btn-success" disabled>Approved</button></td>
<% end %>

<td><%= link_to 'Edit', edit_phase_path(phase), class: "btn btn-secondary" %></td>
<td><%= link_to 'Delete', phase_path(phase),
      method: :delete,
      data: { confirm: 'Are you sure?' }, class: "btn btn-danger", remote: true %>
      </td>

app/views/phases/add_engineer.html.erb
<%= render 'phase_details'%>

<section >

  <h2>Add Engineer to Phase</h2>

  <table class="table table-hover add-engineer-table">
    <thead>
      <tr>
        <th scope="col">User Name</th>
        <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
        <% all_engineer.each do |x| %>
          <tr>
          <td><%= x.user_name %></td>
          <% if @phase.assigned_engineer?(x) %>
            <td><%= link_to 'Remove', phase_remove_engineer_from_phase_path(@phase, user_id: x.id) ,
              id: "remove_engineer_#{x.id}", method: :patch,
              data: { confirm: 'Are you sure?' }, class: "btn btn-danger", remote: true %></td>
          <% else %>
            <td><%= link_to 'Add', phase_add_engineer_to_phase_path(@phase, user_id: x.id) , class: "btn btn-secondary", id: "add_engineer_#{x.id}", method: :patch, remote: true %></td>
          <% end %>
        </tr>
        <% end %>
    </tbody>
  </table>
</section>

<%= render 'shared/back_navigation', path: lead_phases_path(@phase.lead)  %>

app/views/phases/add_engineer_to_phase.js.erb
$("#add_engineer_<%= params[:user_id] %>").replaceWith('<%= link_to 'Remove', phase_remove_engineer_from_phase_path(@phase, user_id: params[:user_id]) ,
        method: :patch, id: "remove_engineer_#{params[:user_id]}",
        data: { confirm: 'Are you sure?' }, class: "btn btn-danger", remote: true %>')

app/views/phases/approve.js.erb
$("#phase_approve_<%= @phase.id %>").replaceWith('<button class="btn btn-success" disabled>Approved</button>')
$("#add_engineer_<%= @phase.id %>").remove()

app/views/phases/destroy.js.erb
$("#phase_<%= @phase.id %>").remove()

app/views/phases/edit.html.erb
<h3 class="h3 mb-3 font-weight-normal">Edit Phase</h3>
<%= render "phase_form", phase: @phase %>

<%= render 'shared/back_navigation', path: lead_phases_path(@phase.lead)  %>

app/views/phases/index.html.erb
<h2>Phases</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Sr.</th>
      <th scope="col">Phase Type</th>
      <th scope="col">Start Date</th>
      <th scope="col">End Date</th>
      <th scope="col">Assigned To</th>
      <th scope="col">Assigned Engineer</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
  </tr>
  </thead>
  <tbody>
    <% @id = 0 %>
    <% @phases.each do |phase| %>
      <% @id += 1%>
      <tr id="phase_<%= phase.id %>">
        <th scope="row"><%= @id %></th>
        <td><%= phase.phase_type %></td>
        <td><%= phase.start_date %></td>
        <td><%= phase.end_date %></td>
        <td><%= phase.user.user_name %></td>
        <td>
          <%= find_all_engineer_of_phase(phase.assigned_engineer) if phase.assigned_engineer %>
        </td>
        <td><%= link_to 'Add Engineer', phase_new_engineer_path(phase), class: "btn btn-secondary", id: "add_engineer_#{phase.id}" if check_add_engineer(phase, current_user) %></td>
        <td><%= link_to 'View',phase_path(phase), class: "btn btn-primary" %></td>
        <% if policy(Phase).update? %>
          <%= render 'restricted_options', phase: phase %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'shared/back_navigation', path: lead_path(params[:lead_id])  %>

app/views/phases/new.html.erb
<h3 class="h3 mb-3 font-weight-normal">Create Phase</h3>
<%= render "phase_form", phase: @phase %>

<%= render 'shared/back_navigation', path: lead_path(params[:lead_id])  %>

app/views/phases/remove_engineer_from_phase.js.erb
$("#remove_engineer_<%= params[:user_id] %>").replaceWith('<%= link_to 'Add', phase_add_engineer_to_phase_path(@phase, user_id: params[:user_id]) , class: "btn btn-secondary", id: "add_engineer_#{params[:user_id]}", method: :patch, remote: true %>')

app/views/phases/show.html.erb
<%= render 'phase_details'%>
<hr>
<%= render 'all_comments' %>